from migrations.seeders.user import *
from migrations.seeders.system_phone import *
from migrations.seeders.partner import *
from migrations.seeders.registration import *
from migrations.seeders.program import *
from migrations.seeders.language import *
from migrations.seeders.content_version import *
from migrations.seeders.content import *
from migrations.seeders.user_program import *
from migrations.seeders.module import *
from migrations.seeders.module_content import *
from migrations.seeders.program_module import *
from migrations.seeders.program_sequence import *
from migrations.seeders.call_log import *
