"""empty message

Revision ID: 4db8d0820cc3
Revises: 4babe970374b
Create Date: 2024-01-22 09:23:58.247740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4db8d0820cc3"
down_revision = "4babe970374b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact_fields_mapping")
    op.drop_table("user_group")
    op.drop_table("user_custom_fields")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_custom_fields",
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("registration_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "user_phone", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "flow_run_uuid", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "field_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "field_value", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registration.id"],
            name="user_custom_fields_registration_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_custom_fields_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_custom_fields_pkey"),
    )
    op.create_table(
        "user_group",
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_phone", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("registration_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "group_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "group_uuid", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registration.id"],
            name="user_group_registration_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_group_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_group_pkey"),
    )
    op.create_table(
        "contact_fields_mapping",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "field_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "field_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "mapped_table_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "mapped_table_column_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "mapped_table_column_value",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expected_field_data_type",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expected_field_value",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="contact_fields_mapping_pkey"),
    )
    # ### end Alembic commands ###
