"""empty message

Revision ID: 7988c819f091
Revises: ec9dc2fe754c
Create Date: 2023-10-11 16:51:32.752053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7988c819f091"
down_revision = "ec9dc2fe754c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_version", sa.Column("new_status", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_version", "new_status")
    # ### end Alembic commands ###
