name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - feature/414/install-packages-and-create-database-migrations

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
